services:
  openvpn-client:
    image: openvpn-client:latest
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - ALLOWED_SUBNETS=192.168.10.0/24
      - CONFIG_FILE=client.ovpn
    volumes:
      - ./local:/config # Mount 'local' directory to container for ovpn configuration files
    ports:
      - "3128:3128" # Port mapping for Squid proxy
    dns:
      - 8.8.8.8 # Google DNS
      - 1.1.1.1 # Cloudflare DNS
    restart: unless-stopped
  squid:
    image: squid:latest
    container_name: squid
    # Use the network stack of the openvpn-client service
    network_mode: service:openvpn-client
    restart: unless-stopped