services:
  openvpn-client:
    image: openvpn-client:1.0
    container_name: openvpn-client
    build:
      dockerfile: Dockerfile
      context: ovpn-build
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - ALLOWED_SUBNETS=192.168.10.0/24
      - CONFIG_FILE=client.ovpn
    volumes:
      - ./local:/config
    ports:
      - "3128:3128"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
  squid:
    image: squid:1.0
    container_name: squid
    network_mode: service:openvpn-client
    build:
      dockerfile: Dockerfile
      context: squid-build